print("My Name is Gaurav Jayant")
print("I am a Python Developer,7")
print("gaurav \n jayant")

print("Name\tAge\tCity")
print("Gaurav\t30\tDelhi")
print(17*36)
print("I am a good boy \n Gaurav is also good boy")
print("Hey I am here",6,7,sep="~",end="009\n")
print("gaurav")